
version: '3.3'
services:
  sns:
    image: s12v/sns
    ports:
    - "9911:9911"
    volumes:
    - ./sns/db.json:/etc/sns/db.json
    depends_on:
    - sqs
  sqs:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./sqs/elasticmq.conf:/opt/custom/elasticmq.conf