
version: '3.3'
services:
  sns:
    image: s12v/sns
    ports:
    - "9911:9911"
    volumes:
    - ./sns/db.json:/etc/sns/db.json
    depends_on:
    - sqs
  sqs:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./sqs/elasticmq.conf:/opt/custom/elasticmq.conf
  kafka:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000